language: ruby
cache: bundler
rvm:
  - 2.2.3
  - 2.2.0
  - 2.1.7
  - 2.0.0
script: 'bundle exec rake'
before_install:
  - gem uninstall libxml-ruby
  - gem update bundler
notifications:
  email:
    recipients:
      - jatesins@ncsu.edu
    on_failure: change
    on_success: never