language: ruby
cache: bundler
rvm:
  - jruby
  - 2.1.2
  - 2.0.0
  - 1.9.3
script: 'bundle exec rake'
notifications:
  email:
    recipients:
      - jatesins@ncsu.edu
    on_failure: change
    on_success: never